services:
  - type: web
    name: ratesmart-backend
    env: python
    buildCommand: "echo 'No build needed'"
    startCommand: "python debug_server.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,ratesmart.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: ratesmart-db
          property: connectionString

databases:
  - name: ratesmart-db
    databaseName: ratesmart
    user: ratesmart