services:
  - type: web
    name: ratesmart-backend
    env: python
    plan: free
    buildCommand: "cd backend && chmod +x build.sh && ./build.sh"
    startCommand: "cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: True
      - key: CORS_ALLOWED_ORIGINS
        sync: false