services:
  - type: web
    name: ratesmart-backend
    env: python
    buildCommand: "pip install gunicorn"
    startCommand: "gunicorn test_wsgi:application --bind 0.0.0.0:$PORT --log-level debug --access-logfile - --error-logfile -"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,ratesmart.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: ratesmart-db
          property: connectionString

databases:
  - name: ratesmart-db
    databaseName: ratesmart
    user: ratesmart